### ISSUE TITLE
Kontrola správného rozložení dvoustran

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/tp-zpevnik#10]
Přidat možnost kontroly správného rozložení dvoustran (levá - pravá) při oboustranném sázení.

**Comment by vasekp** [comment]
Kontrolu nebo automatické řešení? Přemýšlel jsem o tom a říkal jsem si, že nechat to na počítači není tak jednoznačné: co je správné řešení, když dvoustránková píseň nevychází správně? Počkat s ní (a případně s frontou dalších přímo následujících) na příští jednostránkovou nebo odložit zatím tu z levé strany? Co když je ta chybná dvoustránka první nebo poslední ve zpěvníku? Co když něco vyjde na ještě víc než dvě strany?

Dal bych tam jen varování (s dočasným zastavením překladu) a vyřeší ať si to uživatel sám. To se dá udělat i přímo v TeXu.

**Comment by karel-brinda** [comment]
Předpokládal jsem, že pokud bude kontrola zapnutá, tak to v případně špatného rozložení spadne a vypíše všechny písně, které jsou špatně (a uživatel si to vypermutuje, jak chce).

**Comment by vasekp** [comment]
No, když to uděláš pomocí `\errmessage`, jediný rozdíl je, že to napíše každou píseň zvlášť a uživatel ji může „odklepnout“ a pokračovat, nebo překlad přerušit.

**Comment by vasekp** [comment]
Jestli nevadí, že bez assignmentu, udělal jsem na to opravu :-) Jestli nebudeš chtít, nezlob se a ten pull request prostě odmítni.
