### ISSUE TITLE
obsah by měl obsahovat odkazy na písničky

### ISSUE THREAD

**Issue by jhajas** [karel-brinda/tp-zpevnik#12]
Šlo by zařídit, aby v indexech byl odkaz na stránku s písničkou? Tedy ne jen číslo stránky, ale rovnou link (v PDF)?

**Comment by karel-brinda** [comment]
Uff, tak jsem myslel, že to bude triviální a není (hrál jsem si s tím včera asi 1,5 hodiny a nevyřešil to). Normálně stačí přidat balíček `hyperref`, jenomže on pravděpodobně není kompatibilní s balíčkem, který je použit pro podporu více indexů (nebo hyperlinky neprojdou přes ten můj řadící skript). Musím se pak na to ještě někdy podívat pořádně a zkusit indexy generovat něčím jiným.

**Comment by jhajas** [comment]
Vitej do klubu. Ja jsem taky na tom stravil asi hodinu nez jsem te o to pozadal :(

Nesloby treba udelat misto toho proste obsah s linkami?

**Comment by vasekp** [comment]
Skoro to mám. Problém je se spojováním souborů v PyPDF. Konkrétně se mi povedlo se dopátrat k jádru, co se tam chová špatně, a myslím si, že je to v PyPDF bug. Zkusím vyřešit spojování souborů jinak.
