### ISSUE TITLE
Pravidla pro přidávání nových písní

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/tp-zpevnik#20]
Sepsat pravidla (samostatný MarkDown dokument), co musí splňovat písně v TP zpěvníku (formát akordů, malá/velká písmena, atd.).

**Comment by karel-brinda** [comment]
@vasekp Vašku, sepsal bys je, prosím?

**Comment by vasekp** [comment]
Pravidla jsem přidal do `Readme.md`, aby byla hned vidět (a také protože tam už relevantní sekce existovala, jen byla velmi krátká). Znamená to, že dvě poznámky (mollové akordy a středoevropská notace) teď zmiňuje dvakrát, ale to podle mě není na škodu. Pokud bys z toho raději viděl samostatný dokument, mělo by být velmi snadné to vystřihnout a `Readme.md` tím vrátit prakticky do původního stavu.

**Comment by vasekp** [comment]
-> #21
