### ISSUE TITLE
Nefunkčnost překladu po LaTeX chybě

### ISSUE THREAD

**Issue by vasekp** [karel-brinda/tp-zpevnik#22]
Když při `snakemake AllSongs` nastane TeX chyba, `snakemake` mi neumožňuje na ni TeXu odpovědět. Volání `snakemake` opakované po přerušení překladu `Ctrl+C` skončí Python chybou:

```
! Undefined control sequence.
...
? ^CTerminating processes on user request.
Removing output files of failed job AllSongs since they might be corrupted:
_TP_zpevnik_komplet.pdf

$ snakemake -f AllSongs
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/snakemake/__init__.py", line 379, in snakemake
    greediness=greediness)
  File "/usr/lib/python3.3/site-packages/snakemake/workflow.py", line 292, in execute
    self.persistence.lock()
  File "/usr/lib/python3.3/site-packages/snakemake/persistence.py", line 84, in lock
    if self.locked:
  File "/usr/lib/python3.3/site-packages/snakemake/persistence.py", line 66, in locked
    for f in lock:
  File "/usr/lib/python3.3/codecs.py", line 300, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 149: invalid start byte
```

Chyba přetrvává, dokud nesmažu veškerý obsah `.snakemake` a `cache.TP_zpevnik_komplet`.

**Comment by vasekp** [comment]
Workaround: `snakemake -s Snakefile.AllSongs` odpovědět TeXu umožňuje.

**Comment by karel-brinda** [comment]
Asi vyhodím ten Snakefile pro všechny zpěvníky a udělám z toho bash skript. Se Snakemakem volajícím Snakemake nemám dobré zkušenosti :).

**Comment by vasekp** [comment]
Ten skript se zasekne taky stejným způsobem (co je horší, nejde z toho stavu přerušit pomocí `Ctrl+C`). Nebo když `snakemake` zavolám z `make`. Překládat jednotlivé `Snakefile` po jednom z příkazové řádky zůstává zatím jediným řešením, kde můžu po TeX chybě pokračovat.

**Comment by vasekp** [comment]
Dotrasoval jsem se k rozdílu, že při chybě a očekávání vstupu z terminálu je `pstree`

```
snakemake-+-snakemake---bash---xelatex---xdvipdfmx
          `-2*[{snakemake}]
```

ve stavu S (interruptible sleep), ale při přidání jedné vrstvy (`bash` nebo `make`) na začátek je od prvního `snakemake` dál T (stopped). A nereaguje na `SIGCONT`, který by ho normálně převedl z T do S. Myslím, že se to stává, když se probouzející proces pokouší o vstup z terminálu, který už používá některý běžící.

**Comment by vasekp** [comment]
Tak prý programy se vstupem jsou mimo účely Snakemake. Workaround zde:
https://bitbucket.org/johanneskoester/snakemake/issues/239/shell-commands-requiring-terminal-input
Otázkou je, jestli ho chceme.

Jinou možností by bylo volat `tex -interaction nonstopmode` nebo použít odpovídající `\nonstopmode` ve zdrojáku. Pak se zpětně prolistovat, co se kde vypsalo na terminál. Chybová hláška bude pravděpodobně někde u konce. Vyzkouším a kdyžtak pošlu.
