### ISSUE TITLE
AllSongs nerozeznává nově přidané písničky

### ISSUE THREAD

**Issue by vasekp** [karel-brinda/tp-zpevnik#23]
Nové písničky se neobjeví v "kompletním" zpěvníku, dokud nesmažu (minimálně) `cache.TP_zpevnik_komplet/_TP_zpevnik_komplet.tex`:
1. Snakemake je přesvědčený, že se nic nezměnilo.
   
   ```
   $ vi Josef_Zíma,_Karel_Štědrý____Milenci_v_texaskách.tex (nová písnička)
   $ snakemake AllSongs
   Nothing to be done.
   ```
2. Když ho k překladu donutím, nové písničky si všimne, přiřadí ji `cache` soubor, ale nezařadí do obsahu:
   
   ```
   $ snakemake -f AllSongs
   Provided cores: 1
   Rules claiming more threads will be scaled down.
   Job counts:
       count   jobs
       1   AllSongs
       1
   rule AllSongs:
       output: _TP_zpevnik_komplet.pdf
   Provided cores: 1
   Rules claiming more threads will be scaled down.
   Job counts:
       count   jobs
       1   all
       1   main_pdf
       1   song_tex
       3
   rule song_tex:
       input: tp-songs/02_pop_rock/Josef_Zíma,_Karel_Štědrý____Milenci_v_texaskách.tex, /home/vasek/misc/zpevniky/tp-zpevnik/Snakefile.AllSongs
       output: cache.TP_zpevnik_komplet/0_Josef_Zíma,_Karel_Štědrý____Milenci_v_texaskách.tex
   1 of 3 steps (33%) done
   rule main_pdf:
   [[[...]]]
   cache.TP_zpevnik_komplet/0_Jiří_Suchý____Zlatý_slunce_nad_hlavou.tex, cache.TP_zpevnik_komplet/0_Josef_Zíma,_Karel_Štědrý____Milenci_v_texaskách.tex, cache.TP_zpevnik_komplet/0_Kabát____Láďa.tex,
   [[[...]]]
   (./0_Jiří_Suchý____Zlatý_slunce_nad_hlavou.tex [241]) (./0_Kabát____Láďa.tex [242])
   [[[...]]]
   ```
3. Teprve po smazání `cache.TP_zpevnik_komplet/_TP_zpevnik_komplet.tex` (nebo celého adresáře) a novém překladu se písnička dostane do `_TP_zpevnik_komplet.pdf`.

**Comment by vasekp** [comment]
Dodatek: můj normální postup je jen krok 3. Když je sleduji v uvedeném pořadí, tj. přeložím, smažu .tex, přeložím, dostanu tuhle chybu:

```
$ rm cache.TP_zpevnik_komplet/_TP_zpevnik_komplet.tex; snakemake -f AllSongs
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
    count   jobs
    1   AllSongs
    1
rule AllSongs:
    output: _TP_zpevnik_komplet.pdf
IncompleteFilesException:
The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with

    snakemake --cleanup-metadata <filenames>

To re-generate the files rerun your command with the --rerun-incomplete flag.
Incomplete files:
_TP_zpevnik_komplet.pdf
Error in job AllSongs while creating output file _TP_zpevnik_komplet.pdf.
RuleException:
CalledProcessError in line 14 of /home/vasek/misc/zpevniky/tp-zpevnik/Snakefile:
Command 'snakemake -s Snakefile.AllSongs' returned non-zero exit status 1
  File "/home/vasek/misc/zpevniky/tp-zpevnik/Snakefile", line 14, in __AllSongs
Removing output files of failed job AllSongs since they might be corrupted:
_TP_zpevnik_komplet.pdf
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
```

Nevím, nakolik to je relevantní, a je jasné, že je to kvůli mému nestandardnímu zásahu (smazání souboru z mezipaměti), takže tohle není stížnost. Ale říkal jsem si, že by to mohlo dát nějaké relevantní ladicí informace.

**Comment by karel-brinda** [comment]
Mohl bys to teď otestovat? Teď už by to mělo běhat (je to větev timestamp_bug).

**Comment by vasekp** [comment]
Nemůžu, mám zrovna snake_incl brutálně "rozdělaný" a ne ve stavu, kdy bych na něj dal commit. Zkusím, jakmile budu moct.

**Comment by karel-brinda** [comment]
Stačí, když si překopíruješ celý adresář jinam, obnovíš checkoutem původní verzi všeho a změníš větev. Jinak taky by to mělo jít s `git worktree` (https://github.com/blog/2042-git-2-5-including-multiple-worktrees-and-triangular-workflows), ale ve svém gitu tenhle subcommand ještě nemám.

**Comment by vasekp** [comment]
Bylo to pár úprav, tak jsem je vložil ručně. A zdá se, že tohle funguje skvěle jak na nové písničky, tak na timestamp existujících! :+1:
