### ISSUE TITLE
Možnost přeložit vybrané písně do samostatných PDF souborů

### ISSUE THREAD

**Issue by jhajas** [karel-brinda/tp-zpevnik#28]
Hodila by se nám někdy možnost vybrané písničky (třeba specifikované v Snakefile.TPBAND) přeložit každou do zváštního PDF souboru. Lépe by se pak s tím pracovalo na zkoušce a při trénování doma.

Třeba to už pomocí snakemake nějak jde řešit, ale nepřisel jsem na to jak na to...

**Comment by karel-brinda** [comment]
Tahle feature se objeví jako vedlejší efekt #10. Na to totiž bude potřeba přesně tohle -- přeložit každou píseň navíc jako samostatné PDF. Kromě toho se to bude hodit i na např. posílání písní mailem.

**Comment by vasekp** [comment]
@karel-brinda Ne se současným řešením #10. Popřemýšlím, jak jinak to udělat elegantně. Ale nějak nechápu účel ticketu – je problém si z PDF vytisknout (případně "vytisknout do souboru") jen nějaký rozsah stránek? Nebo při prohlížení na počítači místo otevření relevantního souboru skočit `Ctrl+End` na poslední stránku do rejstříku a kliknout na odkaz (když už existují)? Jaké je typické použití, kde by generování samostatných souborů pomohlo?

**Comment by karel-brinda** [comment]
Mně taky tahle funkce chybí. Např. když člověk přidává novou píseň a chce mít v PDF jenom ji (např. ji průběžně posílá někomu pro kontrolu mailem). Samozřejmě se to dá řešit např. pomocí tisku do PDF, ale  zdržuje to.

**Comment by karel-brinda** [comment]
Nejlepší by bylo udělat pro to další option (= vysázej i jednotlivá PDF pro všechny písně do keše).

**Comment by vasekp** [comment]
Tak jednu písničku nebo všechny? Pro jednu mi přijde jednodušší zakomentovat všechno ve Snakefile a nechat jen ji. Pokud víc, stejně nebude chtít člověk nejspíš _úplně_ celý zpěvník po jedné, takže do Snakefile stejně bude muset. Jestli jich bude jen pár, co tak na to udělat nějaký jiný seznam, který bude přebíjet (nebo doplňovat) `songs`?

**Comment by vasekp** [comment]
Jiná otázka: je žádoucí, aby ty písničky odpovídaly své podobě ve zpěvníku (co se týká levé / pravé strany, čísla stránky a čísla písničky), aby z nich šel zase "poskládat"?
Já bych to chápal tak, že když chce člověk písničku samotnou, ty ostatní ani kontext ho nezajímají a hodně věcí by se mělo lišit: žádný cover, žádné záhlaví, žádné číslo písničky ani číslo stránky, implicitně `ONESIDE`. To mi přijde dost důvodů k tomu přistupovat principiálně jinak než jen jednou option navíc.

**Comment by karel-brinda** [comment]
Moje představa je následující: pokud by byla zapnutá tato volba, tak by se pro všechny písně daného zpěvníku vygenerovaly do keše také PDF pro jednotlivé písně v módu onepage bez coveru, rejstříku, čísla, atd. Mělo by to být co nejjednodušší na používání. Já osobně to budu používat hlavně u toho zpěvníku se všemi písněmi.

**Comment by karel-brinda** [comment]
Co se týče rychlosti, tak by to velké zpomalení být nemělo, protože to bude nezávislé a Snakemake to bude dělat paralelně.

**Comment by vasekp** [comment]
OK. To nebude těžké.

**Comment by karel-brinda** [comment]
@vasekp  Ještě znovu otevírám tenhle ticket. Nějak jsem to nezkontroloval pořádně a je tam drobný zádrhel. Ta vysázená jednotlivá PDF se objevují v hlavním adresáři, ale měla by zůstat v keši.

Jedním z důvodů je to, že když se spustí sazba několika zpěvníků v jednu chvíli, tak to nedopadne dobře (několik zpěvníků bude chtít v jednu chvíli vytvořit to samé PDF). Navíc to také dost zaneřádí hlavní adresář.

**Comment by vasekp** [comment]
Tohle bude hned. Jen pro pořádek otevírám "doopravdy".

S hlavním adresářem to bylo nedorozumění, myslel jsem právě, že v cache to nikdo hledat nebude. Ale s těmi konflikty to dává víc smyslu.

Speaking of cache, ten je touhle dobou zaneřáděný už strašně. Zvlášť těmi podtržítky a tím, že každý soubor tam je s pěti všelijakými příponami. Navrhuji vygenerované soubory, které ničemu nepomůžou při opětovném překladu (`.log`, `.out`, `.aux` kromě hlavního) při úspěšném překladu smazat pomocí Snakemake příkazu `temp`, souhlasíš?

**Comment by vasekp** [comment]
@karel-brinda Mimochodem, jaké jsou důvody k těm jmenným konvencím? Proč podtržítko na začátku? Proč `0_` u písniček?

**Comment by vasekp** [comment]
Počkat, zapomněl jsem napsat, že ten adresář jde nastavit. Je na to proměnná `singles_dir`. Teprve když není nastavená, default je základní adresář.

**Comment by vasekp** [comment]
S novou revizí je tohle zakomentované. PDF jednotlivých písniček se generují podle vzoru

```
cache.zpevnik/_single_Autor____Název.pdf
```

**Comment by vasekp** [comment]
Ta option má zádrhel navíc. Udělám na to vlastní ticket.

**Comment by vasekp** [comment]
Neudělám, vymyslel jsem to jinak :-)
