### ISSUE TITLE
Nesmyslná čísla stránek

### ISSUE THREAD

**Issue by vasekp** [karel-brinda/tp-zpevnik#41]
Čísla stránek ve zpěvníku obecně nejsou, ale z nějakého důvodu se objevují na první stránce každého z rejstříků (na ostatních zase ne). Chceme je?

**Comment by karel-brinda** [comment]
Objevovat by se tam správně neměla. Čísla stran se od posledního oficiálního zpěvníku přestala používat.

**Comment by vasekp** [comment]
Tahle chyba je v `index.sty`:

``` tex
\thispagestyle{plain}%
```

Jak si poradit se situací, kdy by byl potřeba zásah do systémových souborů? Jako efektivní řešení vymezené na `template.tex` mě napadá předefinovat `\thispagestyle`, je to hack, ale vedlejší účinky opravdu nevidím. Souhlas?
