### ISSUE TITLE
NeA4 cover se posadí do levého horního rohu

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/tp-zpevnik#44]
Pokud cover není přesně A4, vloží se do A4 do levého horního rohu (viz aktuální cover TP bandu od @jhajas).

Možnosti, jak to řešit (jsou nějaké další?):
1. centrovat doprostřed
2. roztáhnout na A4
3. srovnat danou stránku na velikost stránky coveru
4. je na zodpovědnosti autora coveru, aby si pohlídal jeho velikost

Osobně mi přijdou nejjednodušší varianty 1 a 4.

**Comment by vasekp** [comment]
**Mnohem** jednodušší je centrování, jestli by @jhajas vyhovovalo.

**Comment by vasekp** [comment]
I když tohle je LaTeX. Podívám se i na možnost roztažení a nabídnu na výběr.

**Comment by vasekp** [comment]
Přemýšlel jsem i o možnosti roztažení, ale přijde mi nepraktická, protože kdyby poměr stran nebyl 1:√2, nechávalo by to možnosti roztáhnout přesto (a riskovat nepřirozeně vypadající výsledek) nebo roztáhnout nejvíc, jak jde se zachováním aspect ratio, a horizontálně nebo vertikálně nechat bílý pruh – a to mi nepřijde lepší než ho prostě nechat po celém obvodu.
