### ISSUE TITLE
Logika adresářové struktury

### ISSUE THREAD

**Issue by vasekp** [karel-brinda/tp-zpevnik#49]
Ahoj, navrhuji novou strukturu adresářů:
- `cache.muj_novy_zpevnik` → `cache/muj_novy_zpevnik`
- `_muj_novy_zpevnik.pdf` → `output/muj_novy_zpevnik.pdf`
- `Beatles____Love_me_do.pdf` → `output/muj_novy_zpevnik/Beatles____Love_me_do.pdf`

Takže jediné generované adresáře v kořeni by byly `cache` a `output`. PDF by se nemíchala se Snakefile, `Readme.md` a bashovými skripty a nemusela hledat podle podtržítek. Úklid by byl transparentní a při ručním provádění okamžitý.

Taky by bylo fajn přejmenovat `tpcb` na něco, co nezačíná na `tp` (a pokud možno ani na `t`) pro snazší autocomplete. Nebo ať si začíná, ale má pak taky pomlčku jako ty ostatní podadresáře. Vždycky, když se na klávesnici musím natáhnout na pomlčku nebo podtržítko, umře někde koťátko!

Názory?

**Comment by karel-brinda** [comment]
Se změněnou strukturou adresářů souhlasím, je dobře navržená. Podtržítka, nuly, atd. byly kvůli tomu, že někdy špatně Snakemake míchal různé soubory do špatných pravidel (výsledné pdf, prázdná stránka, atd.). Nepamatuju si detaily, chce to akorát otestovat, jestli to bude fungovat.

TPCB je zkratka pro Technická Přestávka ChordBook. Název by měl zůstat, protože v určitý moment z toho bude normální pythonový balík (původně to dokonce byl samostatný repozitář, pro zjednodušení vývoje jsem to ale zařadil přímo do repozitáře TP zpěvníku). Můžeme to přejmenovat `tpcb` -> `TPCB`.

**Comment by vasekp** [comment]
Dobrá, přídám taky všechno do `vasek-jednotlivé` (PR #51).

**Comment by vasekp** [comment]
S tím problémem jsem se asi setkal, dost mě tehdy zmátl, ale vím už, jak na něj.
