### ISSUE TITLE
Autodeploy posledních PDF všech zpěvníků do větve gh-pages

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/tp-zpevnik#56]
Poslední verze zpěvníku se bude automaticky uploadovat na web.

Howto: https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by karel-brinda** [comment]
Prvni fungujici prototyp: http://tp-zpevnik.surge.sh/. Kod je ve vetvi `surge`.

**Comment by vasekp** [comment]
Bylo by fajn, čistě pro estetické účely, udělat větev `gh-pages` jako sirotka (`git checkout --orphan gh-pages; git rm -rf .; repopulate; git commit -a`). Nebude pak 200 commitů pozadu a několik dopředu, které nikdy nemáme v plánu zařadit do master.

**Comment by karel-brinda** [comment]
Poznámka pro mě:
https://github.com/socrata/dev.socrata.com/blob/1b1f9d6fd617145bacfa92c02dbf9e0b67d4e470/.travis.yml#L27
