### ISSUE TITLE
Travis nepřekládá nové commity

### ISSUE THREAD

**Issue by vasekp** [karel-brinda/tp-zpevnik#58]
Chyba nastává v `apt-get`.

https://travis-ci.org/karel-brinda/tp-zpevnik/jobs/98985595

**Comment by karel-brinda** [comment]
@vasekp Trvá ten problém pořád? Já jsem ho u mých updatů nezaznamenal. Je možné, že se jednalo o krátkodobý problém na Travisu.

**Comment by vasekp** [comment]
Myslím, že jsem to tehdy vyřešil a neoznačil. Udělám teď, otevřít znovu se dá vždycky.

**Comment by vasekp** [comment]
Tuším, že šlo o tohle v `.travis.yml`: https://travis-ci.org/karel-brinda/tp-zpevnik/jobs/98985596
Dávno vyřešené.
