### ISSUE TITLE
TP 2016

### ISSUE THREAD

**Issue by vasekp** [karel-brinda/tp-zpevnik#61]
Ahoj,

bude letošní ročník mít oficiální zpěvník? Tuším, že to závisí na naší akční skupince, a já jsem rozhodně pro. Napadlo mě, kdybychom něchtěli mít velkou ztrátu na tisku, udělat jen pár a dát lidem možnost si před akcí stáhnout jako PDF a přinést na tabletu. I když takhle napsané to nevypadá moc kompatibilní se základní ideou TP :-)

Jestli se osvědčí systém dodatečných balíčků, musíme od příštího roku jeden z nich udělat na zpěvník! Na kolik tak vůbec jedna kopie v nákladech vychází, kolem 200 možná?

Co se týká výběru písniček, co kdybychom každý udělali jednu verzi Snakefile, jak by se nám zpěvník TP2016 líbil, a pak by se to nějak zprůměrovalo? Jestli nebudou námitky, začnu.

**Comment by vasekp** [comment]
@jhajas @karel-brinda @pedrosow

**Comment by karel-brinda** [comment]
@vasekp Poslal jsem ohledně toho e-mail organizátorům (mělo by ti to přijít v kopii), protože to musí zvážit především oni. Čtení TP zpěvníku u táboráku na tabletu mi přijde vyloženě jako anti-TP myšlenka :-). Ale poslat to v předstihu v PDF by určitě stálo za to, protože spousta lidí si to může vytisknout sama (navíc si to můžou chtít vytisknout nějak alternativně -- např. zmenšeně, růžově, zrcadlově, inverzně, vystřihnout neoblíbené písně, apod. :)).

**Comment by jhajas** [comment]
Tento rok se na LTP bohužel nechystám, takže si nejsem jistý jestli bych měl udělat nějaký výběr za sebe.

**Comment by karel-brinda** [comment]
Přidávám @korchi do tohohle vlákna, protože prý bude dělat letošní zpěvník.

**Comment by korchi** [comment]
Ahoj,

 díky za přidání do vlákna. Prošli jsme s Kačkou TP zpěvník (bohužel verzi 2012) a máme navrhy na smazání/přidání písníček do něj. Zkontroloval jsem s aktuálním zpěvníkem 2015 a do seznamu ( https://docs.google.com/spreadsheets/d/1WNUUomW9Gdcp0UhnWvAfuFrvyF2iF6vFBUK3uBq5z2w/edit?usp=sharing ) napsal změny. 
Smazat - písníčky z TP zpěvníku 2015 které navrhujeme smazat protože je málo lidí umí anebo se vůbec nehrajou. Je zbytečné udržovat zpěvník tlustý :)
Přidat - Písníčky které umím a navrhuji je tam přidat protože jsou moc pekné :).

Tímto bych chtěl otevřít diskuzi které písníčky souhlasíte, žeby se měli vymazat a přidat.
Zatím neumim přidávat písníčky do zpěvníku a nemám moc na to čas. Mohl bych někoho požádat o vykonání případných úprav?

Karel

**Comment by karel-brinda** [comment]
@korchi Ahoj, stručná reakce. Zásadní kritérium pro přidání písničky je to, jestli to má v repertoáru někdo z kytaristů, kdo budou na TP. Pokud se písnička akorát někomu líbí, ale nikdo ji nebude hrát (např. protože ji nikdo nezazpívá), tak pak to je ve zpěvníku k ničemu.

Jinak Cikáni, Trubadúrská, Hotel Hillary, Wish you were here, Time, Žízeň, Traktor patří k mým nejhranějším písničkám. Hodinový hotel, Písnička pro tebe, Měsíc byly zase Pepovo. Smoke on the water, Sweet home Alabama, atd. bylo zase Vítkovo. Hard day's night byla zase asi nejhranější beatlesácká obecně. Čili vidíš, že to, co se hraje, není nějaká "objektivní vlastnost", pouze "vlastnost" kytaristy. Abych to shrnul, je potřeba to udělat skupinově s těmi, kdo na tom TP budou hrát.

Navrhuju pro vás následující postup:
1. zjistit si co nejdřív, kdo z kytaristů na TP jede (např. zeptat se účastníků, kdo plánuje hrát na kytaru, ať se přihlásí)
2. udělat nějaký seznam stylem, ať každý z těch lidí dá vědět, co hraje (aby to nebyl akorát odraz jednoho člověka)
3. začít co nejdříve pracovat na těch nových písní, protože to vždycky trvá; postup máte důkladně popsaný v readme, po technické stránce to už je velice jednoduché (nebývalo)

Jinak např. několik Klusů se už jednou ve zpěvníku objevilu, ale spousta lidí ho doslova nesnášela a skoro nikdo ho nehrál, tak se to zase odstranilo (mrkni se např. na http://tp-zpevnik.surge.sh/TP_zpevnik_2011.pdf).

**Comment by karel-brinda** [comment]
@korchi Jinak doporučuju brát jako referenci tenhle: http://tp-zpevnik.surge.sh/TP_zpevnik_2013.pdf (roky 11, 12, 13 je ta samá "modelová řada", 2013 byl nejvyladěnější).

**Comment by korchi** [comment]
Cau,
 souhlasím s tebou že nemá cenu přidávat písníčky které nikdo neumí zahrat (ale psal jsem že mnou navrhnované písníčky umím (občas s rezervami) zahrát. 

Co se týče mazání písníček, procházeli jsme je s Kačkou ani ja ani Kačka je neumíme a proto jsem návrh je smazat napsal sem. Z vyjmenovaných kytaristů (ty, Vítek, Pepa a Vašek) nikdo bohužel nejede :( na TP. Ale dnes jsem se dozvědel že jede Miško a Lukas Hana (neznám) jedou. Chtělo by je přidat do tohoto vlákna aby se podíleli na názoru co nechat/přidat, ale Miško předpokládam umí všechny písníčky :). 

Mohl bys je přidat do vlákna?
Lukas Hana - lukashana@seznam.cz

**Comment by karel-brinda** [comment]
Abych mohl lidi zmiňovat v konverzaci, musí mít účet na Githubu. Jinak tahle diskuze je veřejná, takže se může přidat kdokoliv bez toho, abych ho musel explicitně povolovat.

**Comment by korchi** [comment]
Aha, tak super. Rozeslu jim link

**Comment by korchi** [comment]
Ahoj,
 do dokumentu https://docs.google.com/spreadsheets/d/1WNUUomW9Gdcp0UhnWvAfuFrvyF2iF6vFBUK3uBq5z2w/edit?usp=sharing jsem se zatim vyjádřil já a Lukáš Hána. Ještě by se na to měl podívat Miško a pak se to může dát do kupy a vytvořit nový zpěvník 2016.

**Comment by karel-brinda** [comment]
Jak to chcete mít řazené (mělo by to mít systém)? Jako výchozí Snakefile můžete použít tenhle: http://tp-zpevnik.surge.sh/Snakefile.sablona. Je tam všechno, co je momentálně v repozitáři. Stačí odkomentovat písně, jaké chcete a případně změnit nulu na nenulu, pokud chcete něco posunout. Až to budete uploadovat, tak na to vytvořte novou větev - např. `zpevnik2016`.

**Comment by korchi** [comment]
Pushnul jsme zmeny ve zpevniku pro TP2016 ve vlastnim forku. Karle, je to takhle ok? Jde ti to zkompilovat v poradku?

**Comment by karel-brinda** [comment]
Udělej, prosím, pull request (pro ten tvůj fork) tady v hlavním repozitáři. To samé pro repo `tp-zpevnik-covers`. Momentálně to nepřeložím kvůli chybějícímu PDF obálky.

**Comment by karel-brinda** [comment]
Jinak vidím poznámku "Některé písně (Hotel California, 500 miles a další) nevycházejí správně na dvoustranu, ale v rámci zachování číslování kontrolu vypneme". Pokud tu kontrolu neuděláte, tak se pak ten zpěvník bude strašně špatně používat, protože se bude otáčet během hraní.

**Comment by karel-brinda** [comment]
Ještě jedna poznámka. Bylo by lepší na to udělat větev přímo tady, neforkovat. Měl bys na to mít práva. Uděláš to např. pomocí `git checkout -b tp2016`.

**Comment by korchi** [comment]
K poznamce, ted jsme zkousel opravit aby zadna pisen nebyla na druhe strance, ale to nejni mozne! ;) Jednu opravis a dve se rozbijou. Takze ted dve pisne (california a 500 miles) proste se budou otacet.

**Comment by korchi** [comment]
Mam ted delat jeste vetev, kdyz uz jsem to forknul a pullnul request?

**Comment by karel-brinda** [comment]
To opravování se dělá prohazováním. Jdeš zleva doprava a občas přehodíš jednostránkovou písničku. Větev dělat nemusíš, uděláme ji pak když tak pro opravy. Uploadnul bys tu obálku? Dám ti práva do toho repozitáře a udělej tam na to když tak větev.

**Comment by karel-brinda** [comment]
Mrknu se pak na to zítra ráno, teď jdu na koncert poslechnout si Wish you were here, Time, atd. v originále :).
