### ISSUE TITLE
Tag - hraci

### ISSUE THREAD

**Issue by michalmedvecky** [karel-brinda/tp-zpevnik#74]
Cau

robite super job :)

Nechcete ku kazdej pesnicke pridat tag, kto ju hrava, aby ked bude dalsie TP, vygeneroval sa spevnik podla toho kto tam bude? :)

**Comment by vasekp** [comment]
To mi zní docela dobře. @karel-brinda?

**Comment by karel-brinda** [comment]
Ahoj, souhlasím, že by to bylo užitečné. To tagování by bylo dobré udělat nějak obecněji, nejen adhoc pro tohle issue. Např já si tak pořád trochu sním o #14 , abych si mohl z toho dělat jednoduše automaticky playlisty.

Nemám úplně teď čas tenhle ticket řešit, protože na konci září odesílám první verzi dizertačky (navíc jsem teď zrovna na konferenci v Lyonu), ale když by to někdo implementoval, tak to zařadím do hlavní větve. Jak by se to tagování mělo optimálně řešit - anotace v rámci tex souborů (uvnitř komentářů, v podstatě libovolné seznamy by se pak daly generovat pomocí `find`, `grep`, `awk`) / separátní json / ...? Zkuste dát nějaké návrhy.

**Comment by vasekp** [comment]
Konkrétně tohle bych docela nerad viděl řešené pomocí tagů. Příklad: přijde nový kytarista (a že jich není málo). Bude muset projít každou písničku a přidat k ní svůj tag, jestli ji hraje. Udělat commit s 200+ minimálně modifikovanými soubory a pull request. Staň se tohle se _dvěma_ novými kytaristy za jeden ročník najednou (nebo ještě lépe, s námi samotnými už během implementace), ideálně ještě s úpravami v jedné řádce, a správce repozitáře klepne.

Jestli jde o výběry podmnožin písniček, na to mechanismus už máme a myslím, že funguje dobře. Jediné, co by to následně chtělo, je možnost obsahy `Snakefile` automaticky mergovat. Mám k tomu dvě poznámky:
1. Často se stává, že dva lidi každý hrají rádi stejnou písničku, ale každý v jiné tónině. Nutno říct, že tenhle problém by vzniknul i v prvním řešení. _Návrh řešení:_ v automaticky spojeném zpěvníku veškeré posuny ignorovat nebo mít nějakou "master" verzi (Anděl, Stánky atd.), oproti níž se budou naše osobní výběry jen doplňovat, a akordy se vezmou z ní. Každý pak může dle libosti přivézt svůj osobní upravený zpěvník jako dosud.
2. Pokud bychom to udělali takhle, bylo by fajn mít možnost **ve `Snakefile`** označit písničky, které do souhrnu nepotřebují (třeba je mám jen pro sebe nebo pro jiné akce), protože jinak by bylo třeba udržovat totéž dvakrát a spousta lidí by si to nedala do `.gitignore` nebo lokální větve a byl by z toho jen bordel.

Co se týká metainformací, nějaký návrh jsem dával u #14 (i když konkrétně pro účel řešený tam), tak vznáším zpět k diskusi.

**Comment by michalmedvecky** [comment]
Ja som sa v tom este nevrtal takze o tom prd viem, ale teraz mam vela casu tak sa do toho pozriem :) ale asi mi potrva, kym budem schopny pomoct.

Kazdopadne argument s novym gitaristom a 200 tagmi je lichy. Ten kto tu pesnicku hra a chce hrat, tak sa do nej tagne. A zvlast ak bude contributovat nove, tak sa otaguje rovno v nich. Mozeme tam dat tag `essentials` ktory bude pre pesnicky, ktore hra kazdy (andel, stanky). Pripadne tag `odrhovak` :-)
