### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by vasekp** [karel-brinda/tp-zpevnik#75]
Myslím, že by bylo dobré k projektu přidat nějakou licenci. Říkal jsem o našem zpěvníku kamarádovi a rád by využil nějaké písničky pro svůj, kdyby šlo, z čehož mě ta otázka napadla. Technicky vzato, i když jsme open source, bez licence je to jen "na koukání". Co třeba [MIT](http://choosealicense.com/licenses/mit/)? (`songbook.sty` je LGPL, ale to zbytek neomezuje ani se to na něj nijak automaticky nerozšiřuje.)

**Comment by karel-brinda** [comment]
Jsem taky pro MIT, používám to pro všechny svoje projekty. Je to jedna z nejsvobodnějších licencí, což mi je sympatické (moc nemám rád GPL, protože už příliš omezuje komerční použití).

**Comment by karel-brinda** [comment]
@vasekp @jhajas @korchi @pedrosow Souhlasíte tedy s přidáním MIT licence?

**Comment by jhajas** [comment]
za mě ok

út 22. 8. 2017 v 3:27 odesílatel Karel Břinda <notifications@github.com>
napsal:

**Comment by vasekp** [comment]
Souhlas, díky :-)
