### ISSUE TITLE
Nestažitelná PDF

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/tp-zpevnik#76]
Surge začal plošně blokovat stahování PDF, viz https://github.com/sintaxi/surge/issues/257. Snad se dostaneme na whitelist.

**Comment by killerkiara** [comment]
Hi @sintaxi and thanks for the explanations :) I needed to update my CV on my website and suddenly i could not figure out why it would return me a 404. Could you please whitelist my domain as well? It is chiara.codes. Thanks a lot!

**Comment by karel-brinda** [comment]
Vyřešeno přechodem na Github Wiki.
