### ISSUE TITLE
Nové zpěvníky nejsou publikovány

### ISSUE THREAD

**Issue by vasekp** [karel-brinda/tp-zpevnik#87]
Na adrese http://karel-brinda.github.io/tp-zpevnik/ chybí TP 2020. Do procesu publikace bohužel nevidím dostatečně k tomu, abych dokázal najít příčinu a opravit. Možná souvisí s nefunkčností Travis CI. Šlo by to udělat prosím aspoň ručně?

**Comment by karel-brinda** [comment]
Travis v nějaký moment přestal fungovat. Pokusím se to přesunout na GH Actions (postupně jsem tím nahradil Travis ve většině mých repozitářích). Mimochodem díky za nahrání toho zpěvníku z TP2020!!!

**Comment by karel-brinda** [comment]
Jelikož přegenerování zpěvníků trvá dlouho a dělá se to párkrát za rok max, tak jsem to nahrál ručně. Bude to i do budoucna jednodušší, než se patlat s CI, u kterého se každou chvilku mění rozhraní a parametry služeb.
